### ISSUE TITLE
PhoneGap DeviceReady not firing

### ISSUE THREAD

**Issue by DaAwesomeP** [wendelltron/tekapp#29]
I discovered this while trying to use PhoneGap events to monitor online/offline network events to display an onscreen notification when it loses a connection. This is what i saw in the remote Chrome Debugger:
```
deviceready has not fired after 5 seconds. cordova.js:1169
Channel not fired: onCordovaConnectionReady cordova.js:1162
```
I've never seen this before.

I want to switch to events from the interval for good reason. I left the app running in the background on my phone for a day. It got very warm and the battery suffered. I believe it's because of the intervals.

**Comment by DaAwesomeP** [comment]
I should also explain that I reworked the `$flash_notification` into a JSON-based system with [`FactoryOnscreenNotifications`](https://github.com/wendelltron/tekapp/blob/master/app/scripts/services/factoryonscreennotifications.js). Messages are held in the [JSON file](https://github.com/wendelltron/tekapp/blob/master/app/JSON/notifications/onscreen.json) and added and removed with `FactoryOnscreenNotifications.add(id)` and `FactoryOnscreenNotifications.remove(id)`. Duplicate messages will not be shown. DIssmissable messages are possible. If `remove` is called on a not currently shown messages, then no error will be called.

**Comment by jean1880** [comment]
I'll have to brainstorm some solutions for this, I have had this happen before. I'll dig through phonegap, see what I can do. From my previous excursions with it, it usually had to do with the phone being ready before the script loads. I've also had this creep with with other random phonegap issues, due to phonegap not including plugins as it should etc. As a quick troff chance test, you can remove the android platform, the add the android platform back in and rebuild, sometimes that solves it.

**Comment by DaAwesomeP** [comment]
I'll try that

**Comment by DaAwesomeP** [comment]
Huh. That fixed the errors. Now we just have to solve the problem of the connection detection (it doesn't seem to work).

**Comment by DaAwesomeP** [comment]
I think that I might implement [ngCordova](http://ngcordova.com/). It will provide an easy API for all PhoneGap/Cordova things: Device information, app badges, push notifications, etc. It's all Angular compatible too!
