### ISSUE TITLE
Enable Access Origin: *

### ISSUE THREAD

**Issue by jean1880** [wendelltron/tekapp#37]
@wendelltron In experimenting with various builds, one option we have to boost app performance is to use [steroids](http://www.appgyver.com/steroids), which will give us full, true native menu interfaces, to boost performance. In order to do this, the server should have the access-allow-origin: * that way anyone on the app can query the server. Currently, the app can bypass the XCRF security by querying the server through the native frame, which, currently, does not adhere to those security rules. Changing the access rule will allow the app to query this data if those security setting change natively, 

As it stands, we can continue with the app as is, and it will be functional, just will have a few frame drops on heavy loads.

**Comment by DaAwesomeP** [comment]
I've noticed this problem too. I have to start Chrome in low security mode to test the app before emulating/running it.

I'm a little opposed to Steriods because they lock you in to their proprietary build system. Also, Cordova plugins are not compatible, so we will have to redo the CookieJar. Lastly, have you tried Ionic yet? Even in my browser it was 3x smoother and faster than the Boostrap alternative. I would be happy to witch to it. It's CSS stuff is really the same as Boostrap simply with different names; it just adds more JavaScript options (like the slide menu).

Cordova/Phonegap actually has a specifric option for allowing CORS. See [this line of our `config.xml`](https://github.com/wendelltron/tekapp/blob/master/config.xml#L145). I would think that Steriods would have this option.

**Comment by jean1880** [comment]
Yeah, I don't like the steroids proprietary nature, was a couple days of experimentation that pushed me towards it. I did play with Ionic, but it won't fix the lag I was originally trying to fix.

Just a brief explanation of Ionic performance, the key behind the speed they get lay with css 3d transforms. A lot of what bootstrap uses, (and many other frameworks) is the css transition effects, which applies to the various sliding menus, dropdowns, etc, by default, these transitions execute on the CPU. Ionic, having been built around mobile makes use of a little trick to force the gpu to render all of these transitions, by setting a transform3d(0,0,0) (a trick that I had already applied to our own menu). This greatly improves the performance of the app, and reduces the CPU load. However, in our case, with the large lists of content being loaded asynchronously at the same time that the slides are being fired causes it to hang for a split second, giving a jarring effect, specifically on the main page that displays all of the topics. In this instance, I may be being too much of a perfectionist, and running off on a tangent to save a few frames lol.  
Steroids does implement cordova, and allows manual plugins to be added, which should work with CookieJar (though, I didn't get so far to test  as the way Steroids handles nested apps, actually spinning up a local server to render the page, the allow origin hack does not work, as that was how I was bypassing the security with our app from the start

**Comment by wendelltron** [comment]
I hate allowing CORS orgin of * because of the implications to security for web users. I've had success in the past with allowing localhost as a CORS value; would that work here?
Way back a long time ago, there used to be a very simple corsproxy plugin that would add/strip cors information as necessary before passing it to phonegap. I think, eventually, this became the internal method that cordova uses to fix CORS for all apps. ?

Would have to dig into it a bit more.

**Comment by DaAwesomeP** [comment]
@jean1880 Did you try rendering the template for the topic posts before showing them? Part of the problem may be coming from the `FormatHTML` interval or simply Angular not being able to handle the load completely. This app is *definitely* not so advanced that it would need a full switch from Cordova/Phonegap. Also, Jasny Bootstap and ngFx are addons to Bootstrap that provide the slide menu and animation functions because Bootstrap doesn't support them. So it's not really Boostrap's problem. I see you added an Ionic branch. I'll experiment with it.

@wendelltron remember that we would only need CORS disabled for the JSON APIs and images. That is only if we switch away from Phonegap though. I do agree that CORS is a security advantage though.

**Comment by jean1880** [comment]
I think that our best course of action would be to make a call of where we want it to go. We shouldn't be rebuilding left right and centre all of the time, and each framework has its ups and downs. 
### Steroids
Steroids is a proprietary build process, which is A) a major pain in the ass, and B) as @DaAwesomeP mentioned runs the risk of breaking plugins, however, by utilizing the native menus, as well as potentially naative transitions between pages, we could end up with a much smoother experience for the users.
### Ionic
CSS and Javascript framework, gives a nice boost in performance by utilizing the GPU for all transitions and effects. 

I think ultimately, we should switch away from bootstrap, as it would benefit all the other effects and transition effects in the app, it's just a matter of how far we want to take it.

**Comment by jean1880** [comment]
On a quick note, @DaAwesomeP the ionic branch is only partially implemented, I had stopped once I noticed what they were injecting into the elements, namely the Translate3d(0,0,0) styles, to boost performance, since the menu already was using that kind of abandoned part way in the transition.
